bot:
  username:
  token:

scrum:
  groupIds:
    - "-123153"
  wednesday:
    cronExpression: "0 5 10 ? * WED"
    message: "ğŸ¥³ Ğ¡Ñ€ĞµĞ´Ğ° Ğ¿Ñ€Ğ¸ÑˆĞ»Ğ° - Ğ½ĞµĞ´ĞµĞ»Ñ Ğ¿Ñ€Ğ¾ÑˆĞ»Ğ° ğŸ¥³"
  daily:
    # ĞŸĞ½-Ğ¿Ñ‚ Ğ² 09:59 ĞœĞ¡Ğš
    cronExpression: "0 59 9 ? * MON,TUE,WED,THU,FRI"
    message: "ğŸ— ĞŸĞ¾Ñ€Ğ° Ğ½Ğ° Ğ´ĞµĞ¹Ğ»Ğ¸ ğŸ—"
    link:

meme:
  gateway:
    url: https://meme-api.herokuapp.com

logging.level.ru.frank.reactivetelegrambot.gateway.MemeGateway: DEBUG
